[package]
name = "fastdb-payload-integration-tests"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]
members = [
    "fastdb-sys",
    "fastdb",
]
resolver = "2"

[dependencies]
fastdb = { path = "fastdb" }

[[test]]
name = "compile_query"
path = "../../tests/rust/payload/tests/compile_query.rs"

[[test]]
name = "builder"
path = "../../tests/rust/payload/tests/builder.rs"

[[test]]
name = "runtime"
path = "../../tests/rust/payload/tests/runtime.rs"
