# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _fastdb4py
else:
    import _fastdb4py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



import numpy as np

gtAny = _fastdb4py.gtAny
gtPoint = _fastdb4py.gtPoint
gtLineString = _fastdb4py.gtLineString
gtPolygon = _fastdb4py.gtPolygon
gtNone = _fastdb4py.gtNone
cfF32 = _fastdb4py.cfF32
cfF64 = _fastdb4py.cfF64
cfTx16 = _fastdb4py.cfTx16
cfTx24 = _fastdb4py.cfTx24
cfTx32 = _fastdb4py.cfTx32
cfDefault = _fastdb4py.cfDefault
ftU8 = _fastdb4py.ftU8
ftU16 = _fastdb4py.ftU16
ftU32 = _fastdb4py.ftU32
ftI32 = _fastdb4py.ftI32
ftU8n = _fastdb4py.ftU8n
ftU16n = _fastdb4py.ftU16n
ftF32 = _fastdb4py.ftF32
ftF64 = _fastdb4py.ftF64
ftSTR = _fastdb4py.ftSTR
ftWSTR = _fastdb4py.ftWSTR
ftFeatureRef = _fastdb4py.ftFeatureRef
ftREF = _fastdb4py.ftREF
ginWKT = _fastdb4py.ginWKT
ginWKB = _fastdb4py.ginWKB
ginPoint2 = _fastdb4py.ginPoint2
ginLineString = _fastdb4py.ginLineString
ginRAW = _fastdb4py.ginRAW
class point2_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_fastdb4py.point2_t_x_get, _fastdb4py.point2_t_x_set)
    y = property(_fastdb4py.point2_t_y_get, _fastdb4py.point2_t_y_set)

    @staticmethod
    def make(x, y):
        return _fastdb4py.point2_t_make(x, y)

    def __init__(self):
        _fastdb4py.point2_t_swiginit(self, _fastdb4py.new_point2_t())
    __swig_destroy__ = _fastdb4py.delete_point2_t

# Register point2_t in _fastdb4py:
_fastdb4py.point2_t_swigregister(point2_t)
class chunk_data_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    size = property(_fastdb4py.chunk_data_t_size_get, _fastdb4py.chunk_data_t_size_set)
    pdata = property(_fastdb4py.chunk_data_t_pdata_get, _fastdb4py.chunk_data_t_pdata_set)

    def as_array(self, npType):
        return _fastdb4py.chunk_data_t_as_array(self, npType)

    def to_bytes(self):
        return _fastdb4py.chunk_data_t_to_bytes(self)

    def copy_to_buffer(self, dest_buffer):
        return _fastdb4py.chunk_data_t_copy_to_buffer(self, dest_buffer)

    def __init__(self):
        _fastdb4py.chunk_data_t_swiginit(self, _fastdb4py.new_chunk_data_t())
    __swig_destroy__ = _fastdb4py.delete_chunk_data_t

# Register chunk_data_t in _fastdb4py:
_fastdb4py.chunk_data_t_swigregister(chunk_data_t)
class WxDatabaseBuild(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _fastdb4py.WxDatabaseBuild_swiginit(self, _fastdb4py.new_WxDatabaseBuild())
    __swig_destroy__ = _fastdb4py.delete_WxDatabaseBuild

    def begin(self, cfg):
        return _fastdb4py.WxDatabaseBuild_begin(self, cfg)

    def create_layer_begin(self, layerName):
        return _fastdb4py.WxDatabaseBuild_create_layer_begin(self, layerName)

    def add_field(self, name, ft, vmin=0, vmax=1.0):
        return _fastdb4py.WxDatabaseBuild_add_field(self, name, ft, vmin, vmax)

    def set_geometry_type(self, *args):
        return _fastdb4py.WxDatabaseBuild_set_geometry_type(self, *args)

    def enable_st32(self, b=True):
        return _fastdb4py.WxDatabaseBuild_enable_st32(self, b)

    def set_extent(self, minx, miny, maxx, maxy):
        return _fastdb4py.WxDatabaseBuild_set_extent(self, minx, miny, maxx, maxy)

    def add_feature_begin(self):
        return _fastdb4py.WxDatabaseBuild_add_feature_begin(self)

    def set_field(self, *args):
        return _fastdb4py.WxDatabaseBuild_set_field(self, *args)

    def add_feature_end(self):
        return _fastdb4py.WxDatabaseBuild_add_feature_end(self)

    def create_layer_end(self):
        return _fastdb4py.WxDatabaseBuild_create_layer_end(self)

    def post(self, stream):
        return _fastdb4py.WxDatabaseBuild_post(self, stream)

    def save(self, filename):
        return _fastdb4py.WxDatabaseBuild_save(self, filename)

    def set_geometry_wkt(self, data):
        return _fastdb4py.WxDatabaseBuild_set_geometry_wkt(self, data)

    def set_geometry_wkb(self, *args):
        return _fastdb4py.WxDatabaseBuild_set_geometry_wkb(self, *args)

    def set_geometry_raw(self, *args):
        return _fastdb4py.WxDatabaseBuild_set_geometry_raw(self, *args)

    def set_field_cstring(self, ix, text):
        return _fastdb4py.WxDatabaseBuild_set_field_cstring(self, ix, text)

    def set_field_wstring(self, ix, text):
        return _fastdb4py.WxDatabaseBuild_set_field_wstring(self, ix, text)

# Register WxDatabaseBuild in _fastdb4py:
_fastdb4py.WxDatabaseBuild_swigregister(WxDatabaseBuild)
class WxLayerTableBuild(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def name(self):
        return _fastdb4py.WxLayerTableBuild_name(self)

    def add_field(self, name, ft, vmin=0, vmax=1.0):
        return _fastdb4py.WxLayerTableBuild_add_field(self, name, ft, vmin, vmax)

    def set_geometry_type(self, gt, ct, aabboxEnabled=False):
        return _fastdb4py.WxLayerTableBuild_set_geometry_type(self, gt, ct, aabboxEnabled)

    def enable_st32(self, b=True):
        return _fastdb4py.WxLayerTableBuild_enable_st32(self, b)

    def set_extent(self, minx, miny, maxx, maxy):
        return _fastdb4py.WxLayerTableBuild_set_extent(self, minx, miny, maxx, maxy)

    def setDbIndex(self, ix):
        return _fastdb4py.WxLayerTableBuild_setDbIndex(self, ix)

    def add_feature_begin(self):
        return _fastdb4py.WxLayerTableBuild_add_feature_begin(self)

    def set_field(self, *args):
        return _fastdb4py.WxLayerTableBuild_set_field(self, *args)

    def create_feature_ref(self, ix=-1):
        return _fastdb4py.WxLayerTableBuild_create_feature_ref(self, ix)

    def freeFeatureRef(self, ref):
        return _fastdb4py.WxLayerTableBuild_freeFeatureRef(self, ref)

    def add_feature_end(self):
        return _fastdb4py.WxLayerTableBuild_add_feature_end(self)

    def set_geometry_wkt(self, data):
        return _fastdb4py.WxLayerTableBuild_set_geometry_wkt(self, data)

    def set_geometry_wkb(self, *args):
        return _fastdb4py.WxLayerTableBuild_set_geometry_wkb(self, *args)

    def set_geometry_raw(self, *args):
        return _fastdb4py.WxLayerTableBuild_set_geometry_raw(self, *args)

    def set_field_cstring(self, ix, text):
        return _fastdb4py.WxLayerTableBuild_set_field_cstring(self, ix, text)

    def set_field_wstring(self, ix, text):
        return _fastdb4py.WxLayerTableBuild_set_field_wstring(self, ix, text)

# Register WxLayerTableBuild in _fastdb4py:
_fastdb4py.WxLayerTableBuild_swigregister(WxLayerTableBuild)
class WxDatabase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _fastdb4py.delete_WxDatabase

    def get_layer_count(self):
        return _fastdb4py.WxDatabase_get_layer_count(self)

    def get_layer(self, ix):
        return _fastdb4py.WxDatabase_get_layer(self, ix)

    def tryGetFeature(self, ref):
        return _fastdb4py.WxDatabase_tryGetFeature(self, ref)

    def buffer(self):
        return _fastdb4py.WxDatabase_buffer(self)

    @staticmethod
    def load(filename):
        return _fastdb4py.WxDatabase_load(filename)

    @staticmethod
    def load_xbuffer(pdata):
        return _fastdb4py.WxDatabase_load_xbuffer(pdata)

# Register WxDatabase in _fastdb4py:
_fastdb4py.WxDatabase_swigregister(WxDatabase)
class WxLayerTable(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, impl):
        _fastdb4py.WxLayerTable_swiginit(self, _fastdb4py.new_WxLayerTable(impl))

    def name(self):
        return _fastdb4py.WxLayerTable_name(self)

    def get_geometry_type(self):
        return _fastdb4py.WxLayerTable_get_geometry_type(self)

    def get_field_count(self):
        return _fastdb4py.WxLayerTable_get_field_count(self)

    def get_field_offset(self, ix):
        return _fastdb4py.WxLayerTable_get_field_offset(self, ix)

    def get_feature_byte_size(self):
        return _fastdb4py.WxLayerTable_get_feature_byte_size(self)

    def getExtent(self, minx, miny, maxx, maxy):
        return _fastdb4py.WxLayerTable_getExtent(self, minx, miny, maxx, maxy)

    def get_feature_count(self):
        return _fastdb4py.WxLayerTable_get_feature_count(self)

    def rewind(self):
        return _fastdb4py.WxLayerTable_rewind(self)

    def next(self):
        return _fastdb4py.WxLayerTable_next(self)

    def row(self):
        return _fastdb4py.WxLayerTable_row(self)

    def fetchGeometry(self, cb):
        return _fastdb4py.WxLayerTable_fetchGeometry(self, cb)

    def get_geometry_like_chunk(self):
        return _fastdb4py.WxLayerTable_get_geometry_like_chunk(self)

    def get_field_as_float(self, ix):
        return _fastdb4py.WxLayerTable_get_field_as_float(self, ix)

    def get_field_as_int(self, ix):
        return _fastdb4py.WxLayerTable_get_field_as_int(self, ix)

    def get_field_as_string(self, ix):
        return _fastdb4py.WxLayerTable_get_field_as_string(self, ix)

    def get_field_as_wstring(self, ix):
        return _fastdb4py.WxLayerTable_get_field_as_wstring(self, ix)

    def get_field_as_ref(self, ix):
        return _fastdb4py.WxLayerTable_get_field_as_ref(self, ix)

    def set_feature_cookie(self, cookie):
        return _fastdb4py.WxLayerTable_set_feature_cookie(self, cookie)

    def get_feature_cookie(self):
        return _fastdb4py.WxLayerTable_get_feature_cookie(self)

    def tryGetFeature(self, ix):
        return _fastdb4py.WxLayerTable_tryGetFeature(self, ix)

    def get_field_defn(self, ix):
        return _fastdb4py.WxLayerTable_get_field_defn(self, ix)

    def get_extent(self):
        return _fastdb4py.WxLayerTable_get_extent(self)

    def get_column(self,index):
        class __column_np_interface__:
            def __init__(self, table,index,tystr,address,stride,length):
                self.table  = table
                self.name = table.get_field_defn(index)
                self.index  = index
                self.tystr   = tystr
                self.address= address
                self.stride = stride
                self.length = length
            @property
            def __array_interface__(self):
                """返回一个字典，描述数组的接口"""
                return {
                    'version': 3,
                    'typestr': self.tystr,
                    'shape': (self.length,),  
                    'data':  (self.address, False), 
                    'strides':(self.stride,)
                }
            def as_nparray(self):
                """创建一个numpy数组"""
                return np.array(self,copy=False)

            def create_from_table(table,index):
                fieldfn = table.get_field_defn(index)
                tystr=''
                tp = fieldfn[1]
                if(fieldfn[1]==ftU8):
                    tystr='u1'
                elif (tp==ftU16):
                    tystr='u2'
                elif (tp==ftU32):
                    tystr='i2'
                elif (tp==ftI32):
                    tystr='<i4'
                elif (tp==ftF32):
                    tystr='<f4'
                elif (tp==ftF64):
                    tystr='<f8'

                if(not tystr):
                    return None
                ptr = _fastdb4py.get_swig_ptr_as_long(table.tryGetFeature(0).get_address())
                offset = table.get_field_offset(index)
                ptr+=offset
                return __column_np_interface__(
                        table,index,
                        tystr,ptr,
                        table.get_feature_byte_size(),table.get_feature_count()
                    )
        return __column_np_interface__.create_from_table(self,index)


# Register WxLayerTable in _fastdb4py:
_fastdb4py.WxLayerTable_swigregister(WxLayerTable)
class WxFeature(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def layer(self):
        return _fastdb4py.WxFeature_layer(self)

    def fetchGeometry(self, cb):
        return _fastdb4py.WxFeature_fetchGeometry(self, cb)

    def get_geometry_like_chunk(self):
        return _fastdb4py.WxFeature_get_geometry_like_chunk(self)

    def get_field_as_float(self, ix):
        return _fastdb4py.WxFeature_get_field_as_float(self, ix)

    def get_field_as_int(self, ix):
        return _fastdb4py.WxFeature_get_field_as_int(self, ix)

    def get_field_as_string(self, ix):
        return _fastdb4py.WxFeature_get_field_as_string(self, ix)

    def get_field_as_wstring(self, ix):
        return _fastdb4py.WxFeature_get_field_as_wstring(self, ix)

    def get_field_as_ref(self, ix):
        return _fastdb4py.WxFeature_get_field_as_ref(self, ix)

    def set_feature_cookie(self, cookie):
        return _fastdb4py.WxFeature_set_feature_cookie(self, cookie)

    def get_feature_cookie(self):
        return _fastdb4py.WxFeature_get_feature_cookie(self)

    def get_address(self):
        return _fastdb4py.WxFeature_get_address(self)

    def set_field(self, *args):
        return _fastdb4py.WxFeature_set_field(self, *args)

# Register WxFeature in _fastdb4py:
_fastdb4py.WxFeature_swigregister(WxFeature)
class GeometryUtils(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    minx = property(_fastdb4py.GeometryUtils_minx_get, _fastdb4py.GeometryUtils_minx_set)
    miny = property(_fastdb4py.GeometryUtils_miny_get, _fastdb4py.GeometryUtils_miny_set)
    maxx = property(_fastdb4py.GeometryUtils_maxx_get, _fastdb4py.GeometryUtils_maxx_set)
    maxy = property(_fastdb4py.GeometryUtils_maxy_get, _fastdb4py.GeometryUtils_maxy_set)
    gtype = property(_fastdb4py.GeometryUtils_gtype_get, _fastdb4py.GeometryUtils_gtype_set)
    point = property(_fastdb4py.GeometryUtils_point_get, _fastdb4py.GeometryUtils_point_set)
    points = property(_fastdb4py.GeometryUtils_points_get, _fastdb4py.GeometryUtils_points_set)
    part_length = property(_fastdb4py.GeometryUtils_part_length_get, _fastdb4py.GeometryUtils_part_length_set)
    part_first_point = property(_fastdb4py.GeometryUtils_part_first_point_get, _fastdb4py.GeometryUtils_part_first_point_set)
    part_type = property(_fastdb4py.GeometryUtils_part_type_get, _fastdb4py.GeometryUtils_part_type_set)
    polygon_part_count = property(_fastdb4py.GeometryUtils_polygon_part_count_get, _fastdb4py.GeometryUtils_polygon_part_count_set)
    polygon_first_part = property(_fastdb4py.GeometryUtils_polygon_first_part_get, _fastdb4py.GeometryUtils_polygon_first_part_set)

    def get_point_count(self):
        return _fastdb4py.GeometryUtils_get_point_count(self)

    def part_data(self):
        return _fastdb4py.GeometryUtils_part_data(self)

    def get_part_count(self):
        return _fastdb4py.GeometryUtils_get_part_count(self)

    def get_part_length(self, ix):
        return _fastdb4py.GeometryUtils_get_part_length(self, ix)

    def get_point_at(self, ix):
        return _fastdb4py.GeometryUtils_get_point_at(self, ix)

    def get_part_first_point(self, ix):
        return _fastdb4py.GeometryUtils_get_part_first_point(self, ix)

    def get_polygon_part_count(self, ix):
        return _fastdb4py.GeometryUtils_get_polygon_part_count(self, ix)

    def get_polygon_count(self):
        return _fastdb4py.GeometryUtils_get_polygon_count(self)

    def get_polygon_first_part(self, ix):
        return _fastdb4py.GeometryUtils_get_polygon_first_part(self, ix)

    def np(self):
        return _fastdb4py.GeometryUtils_np(self)

    def udpate_bounding_box(self):
        return _fastdb4py.GeometryUtils_udpate_bounding_box(self)

    def begin(self, aabbox):
        return _fastdb4py.GeometryUtils_begin(self, aabbox)

    def returnGeomrtryPart(self, partType, pts, np):
        return _fastdb4py.GeometryUtils_returnGeomrtryPart(self, partType, pts, np)

    def end(self):
        return _fastdb4py.GeometryUtils_end(self)

    def __init__(self):
        _fastdb4py.GeometryUtils_swiginit(self, _fastdb4py.new_GeometryUtils())
    __swig_destroy__ = _fastdb4py.delete_GeometryUtils

# Register GeometryUtils in _fastdb4py:
_fastdb4py.GeometryUtils_swigregister(GeometryUtils)
class aabbox_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    maxEdge = property(_fastdb4py.aabbox_t_maxEdge_get, _fastdb4py.aabbox_t_maxEdge_set)
    minEdge = property(_fastdb4py.aabbox_t_minEdge_get, _fastdb4py.aabbox_t_minEdge_set)

    def width(self):
        return _fastdb4py.aabbox_t_width(self)

    def height(self):
        return _fastdb4py.aabbox_t_height(self)

    def minx(self):
        return _fastdb4py.aabbox_t_minx(self)

    def miny(self):
        return _fastdb4py.aabbox_t_miny(self)

    def maxx(self):
        return _fastdb4py.aabbox_t_maxx(self)

    def maxy(self):
        return _fastdb4py.aabbox_t_maxy(self)

    def repair(self):
        return _fastdb4py.aabbox_t_repair(self)

    @staticmethod
    def make(*args):
        return _fastdb4py.aabbox_t_make(*args)

    def intersects(self, b):
        return _fastdb4py.aabbox_t_intersects(self, b)

    def contains(self, *args):
        return _fastdb4py.aabbox_t_contains(self, *args)

    def __init__(self):
        _fastdb4py.aabbox_t_swiginit(self, _fastdb4py.new_aabbox_t())
    __swig_destroy__ = _fastdb4py.delete_aabbox_t

# Register aabbox_t in _fastdb4py:
_fastdb4py.aabbox_t_swigregister(aabbox_t)

def get_swig_ptr_as_long(py_obj):
    return _fastdb4py.get_swig_ptr_as_long(py_obj)

