#!/usr/bin/env python3
"""Collect the repository's original vendored license texts and notices."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = "THIRD_PARTY_NOTICES.txt"
LICENSE_DEPENDENCIES = ("yyjson", "double-conversion", "picosha2")
EMBEDDED_DEPENDENCIES = ("gaiageo", "clipper", "gpc")
SOURCE_SUFFIXES = {".c", ".cpp", ".h", ".hpp", ".inl"}


def embedded_notices(root: Path, dependency: str) -> list[tuple[str, bytes]]:
    """Retain the original leading notices used by the Core bundle packager."""
    notices = []
    for source in sorted((root / "fastcarto/lib" / dependency).rglob("*")):
        if source.is_file() and source.suffix in SOURCE_SUFFIXES:
            comment = re.search(rb"/\*.*?\*/", source.read_bytes(), re.DOTALL)
            if comment and re.search(rb"copyright|license", comment.group(), re.IGNORECASE):
                notices.append((source.relative_to(root).as_posix(), comment.group()))
    if not notices:
        raise ValueError(f"Missing vendored license notices: {dependency}")
    return notices


def render_notices(root: Path) -> bytes:
    sections = [
        b"FastDB third-party license texts and source notices\n"
        b"Generated by tools/generate_third_party_notices.py.\n"
        b"The source files identified below remain authoritative; regenerate after vendor updates.\n"
        b"FastDB's own license is distributed separately as LICENSE.\n"
    ]
    originals = []
    for dependency in LICENSE_DEPENDENCIES:
        for filename in ("LICENSE", "UPSTREAM.md"):
            source = root / "fastcarto/lib" / dependency / filename
            originals.append((source.relative_to(root).as_posix(), source.read_bytes()))
    for dependency in EMBEDDED_DEPENDENCIES:
        originals.extend(embedded_notices(root, dependency))
    for path, contents in originals:
        sections.extend([
            b"\n" + b"=" * 78 + b"\nSource: " + path.encode("utf-8") + b"\n\n",
            contents,
            b"\n" if not contents.endswith(b"\n") else b"",
        ])
    return b"".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    expected = render_notices(ROOT)
    destination = ROOT / OUTPUT
    if arguments.check:
        if not destination.is_file() or destination.read_bytes() != expected:
            raise SystemExit(f"{OUTPUT} differs from vendored originals; regenerate it with {Path(__file__).name}")
        print(f"{OUTPUT} matches vendored originals")
    else:
        destination.write_bytes(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
