#!/usr/bin/env python3
"""Embed checked-in payload schema source bytes without interpreting them."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "fastcarto/fastdb/src/payload/spec/EmbeddedSchemas.inc"
SCHEMAS = (
    (
        ROOT / "schemas/fastdb.payload.v1.schema.json",
        "kFastdbPayloadV1Schema",
    ),
    (
        ROOT / "schemas/fastdb.payload.manifest.v1.schema.json",
        "kFastdbPayloadManifestV1Schema",
    ),
)


def format_bytes(data: bytes) -> list[str]:
    lines: list[str] = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return lines


def render() -> str:
    lines = [
        "// Generated by tools/generate_embedded_payload_schemas.py.",
        "// Do not edit by hand.",
        "",
    ]
    for path, symbol in SCHEMAS:
        data = path.read_bytes()
        lines.append(f"static constexpr std::uint8_t {symbol}[] = {{")
        lines.extend(format_bytes(data))
        lines.append("};")
        lines.append(
            f"static constexpr std::uint64_t {symbol}Length = UINT64_C({len(data)});"
        )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in include differs; never write",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != expected:
            print(f"embedded schema drift: {OUTPUT}", file=sys.stderr)
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
